
#注册进eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#配置网关端口号
server:
  port: 8767
spring:
  application:
    name: zuul-server
#配置网关转发详情
zuul:
  routes:
    api-a:
      path: /user/**
      service-id: feign-user-server
    api-b:
      path: /order/**
      service-id: feign-order-server